// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEzePvLxUNZ2pQX7a0z2dYyXGzvOtXnBs',
    appId: '1:108789804073:web:9fd5b4d21d38a376e04038',
    messagingSenderId: '108789804073',
    projectId: 'chat-app-1e228',
    authDomain: 'chat-app-1e228.firebaseapp.com',
    storageBucket: 'chat-app-1e228.firebasestorage.app',
    measurementId: 'G-QP5EMD2ZK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7PtcTwEQrXQzOqPuS3ucXe48pR24VD28',
    appId: '1:108789804073:android:f8ca4f4f0a6a6208e04038',
    messagingSenderId: '108789804073',
    projectId: 'chat-app-1e228',
    storageBucket: 'chat-app-1e228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2MvTSt92EEv8tdSvt3NBLf6PXKIhsXak',
    appId: '1:108789804073:ios:2044283987551246e04038',
    messagingSenderId: '108789804073',
    projectId: 'chat-app-1e228',
    storageBucket: 'chat-app-1e228.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2MvTSt92EEv8tdSvt3NBLf6PXKIhsXak',
    appId: '1:108789804073:ios:2044283987551246e04038',
    messagingSenderId: '108789804073',
    projectId: 'chat-app-1e228',
    storageBucket: 'chat-app-1e228.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEzePvLxUNZ2pQX7a0z2dYyXGzvOtXnBs',
    appId: '1:108789804073:web:943774510edc13c7e04038',
    messagingSenderId: '108789804073',
    projectId: 'chat-app-1e228',
    authDomain: 'chat-app-1e228.firebaseapp.com',
    storageBucket: 'chat-app-1e228.firebasestorage.app',
    measurementId: 'G-4VCRWCJK4Q',
  );
}
